run_name: r50_rand_species_multitask_pretrain_1
seed: 0

hierarchy:
  variant: multitask
  multitask_coeffs: [ 8, 5.65, 4, 2.82, 2, 1.41, 1 ]

optim:
  lr: 0.70
  momentum: 0.925
  weight_decay: 7.5e-5

save:
  interval:
  num_checkpoints_to_keep: 1
  overwrite: true
  wandb: true
