run_name: r50_rand_species_pretrain_multitask
seed: 0

hierarchy:
  variant: multitask
  multitask_coeffs: [ 8, 5.65, 4, 2.82, 2, 1.41, 1 ]

optim:
  lr: 0.70
  momentum: 0.930
  weight_decay: 6.0e-4

save:
  interval:
  num_checkpoints_to_keep: 1
  overwrite: true
  wandb: true
