run_name: r50_inat21
max_duration: 36ep

train_dataset:
  # Image resize size before crop, -1 means no resize
  resize_size: -1
  crop_size: 224
  global_batch_size: 2048

  drop_last: true
  shuffle: true

eval_dataset:
  # Image resize size before crop
  resize_size: 256
  crop_size: 224
  global_batch_size: 2048

model:
  name: resnet50
  variant: full-tuning

optim:
  lr: 2.0
  momentum: 0.875
  weight_decay: 5.0e-4

algorithms:
  - cls: BlurPool
  - cls: ChannelsLast
  - cls: EMA
    args:
      half_life: 100ba
      update_interval: 20ba
  - cls: ProgressiveResizing
    args:
      initial_scale: 0.5
      delay_fraction: 0.4
      finetune_fraction: 0.2
  - cls: LabelSmoothing
    args:
      smoothing: 0.08
  - cls: GradientClipping
    args:
      clipping_type: norm
      clipping_threshold: 2.0
