train_dataset:
  path: rand-species-pretrain

  channel_mean: [ 0.4638, 0.4806, 0.3765 ]
  channel_std: [ 0.2341, 0.2255, 0.2445 ]

eval_dataset:
  path: rand-species-pretrain

  # Use the same as training.
  channel_mean: [ 0.4638, 0.4806, 0.3765 ]
  channel_std: [ 0.2341, 0.2255, 0.2445 ]
