run_name: r50_fast
max_duration: 36ep

model:
  name: resnet50
  variant: full-tuning

optim:
  lr: 2.0
  momentum: 0.875
  weight_decay: 5.0e-4

algorithms:
  - cls: BlurPool
  - cls: ChannelsLast
  - cls: EMA
    args:
      half_life: 100ba
      update_interval: 20ba
  - cls: ProgressiveResizing
    args:
      initial_scale: 0.5
      delay_fraction: 0.4
      finetune_fraction: 0.2
  - cls: LabelSmoothing
    args:
      smoothing: 0.08
  - cls: GradientClipping
    args:
      clipping_type: norm
      clipping_threshold: 2.0
