run_name: r50_inat21_hyperparam_sweep

optim:
  lr: { min: 0.5, max: 2.5, scaling: log }
  momentum: { min: 0.8, max: 0.95, scaling: uniform }
  weight_decay: { min: 1.0e-5, max: 1.0e-3, scaling: log }
