run_name: r50_rand_species_cross_entropy_simpleshot

model:
  variant: simpleshot
  pretrained_checkpoint: wandb://imageomics/hierarchical-vision/r50_rand_species_cross_entropy_pretrain.pt:latest?ep36.pt
